targets:
  $default:
    builders:
      :packageVersionBuilder:
        enabled: true

builders:
  packageVersionBuilder:
    import: "package:mo_school_kiosk/consts/package_version_builder.dart"
    builder_factories: ["packageVersionFactory"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: all_packages