name: mo_school_kiosk
description: A new Flutter project.

publish_to: 'none'

version: 1.4.3+13

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  dart_rss: ^3.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_map: ^3.0.0
  flutter_widget_from_html_core: ^0.14.11
  google_fonts: ^4.0.4
  html: ^0.15.4
  http: ^0.13.3
  image: ^4.1.7
  infinite_carousel: ^1.1.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  latlong2: ^0.8.1
  logger: ^2.2.0
  map_controller_plus:
    git:
      ref: e3618b2
      url: https://github.com/ElvenVillage/map_controller_plus.git
  provider: ^6.1.1
  retrofit: ^4.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  window_manager: ^0.3.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

dependency_overrides:
  latlong2:
    git:
      url: https://github.com/ElvenVillage/dart-latlong.git
  flutter_map:
    git:
      url: https://github.com/ElvenVillage/flutter_map.git
      ref: labels

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/schools/
    - assets/more/
    - assets/sections/
    - assets/logos/
