name: mo_school_kiosk
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  collection: ^1.18.0
  dart_rss: ^3.0.1
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: ^0.14.11
  google_fonts: ^4.0.4
  html: ^0.15.4
  http: ^0.13.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  provider: ^6.1.1
  retrofit: ^4.0.3
  rxdart: ^0.27.7
  shared_preferences: ^2.2.2
  window_manager: ^0.3.8

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/schools/
    - assets/more/
    - assets/sections/
    - assets/logos/
