name: CI

on:
  # push:
    # branches: [ main ]
  workflow_dispatch:

jobs:

  build:
  
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4
         
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v4
            
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.3'

      - name: Build version
        id: getversion
        run: |
          ./debian/version.sh
          echo "::set-output name=version::$(cat ./debian/version)"
          
      - name: Build
        run: |
          sudo apt-get install libgtk-3-0 libblkid1 liblzma5 libgtk-3-dev
          ./debian/version.sh
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          chmod 0775 debian/scripts/postinst
          chmod 0775 debian/scripts/prerm
          flutter build linux
          dart pub global activate flutter_to_debian
          flutter_to_debian
          

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          path: build/linux/x64/release/debian/kiosk-dovuz_${{ steps.getversion.outputs.version }}_amd64.deb
          overwrite: true
          

