name: Windows Build

on:
  # push:
    # branches: [ main ]
  workflow_dispatch:

jobs:

  build:
  
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
         
           
      - name: Flutter action
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
          
      - name: Build
        run: |
          flutter config --enable-windows-desktop
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          dart run build_runner build --delete-conflicting-outputs
          flutter build windows --release
    
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: kiosk-dovuz-windows.zip
          directory: build\windows\x64\runner\Release
          

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          path: build\windows\x64\runner\Release\kiosk-dovuz-windows.zip
          overwrite: true
          

